### ISSUE TITLE
Indicator menu too small

### ISSUE THREAD

**Issue by spacekookie** [Bajoja/indicator-kdeconnect#96] opened 2017-08-22 14:59 UTC
I'm having a weird bug where the context menu by the app-indicator is so small that it has to scroll it's content which makes it almost unusable. I'm on Arch Linux and Cinnamon. And I have a 4K display (which might cause some scaling issues? There is a screenshot below...

![Screenshot](http://i.imgur.com/OtoKapa.png)

**Comment by andyholmes** [comment] 2017-08-22 19:54
@spacekookie I've had similar menu glitches, are you using wayland?

**Comment by Bajoja** [comment] 2017-08-23 20:16
@spacekookie, yes, this is not the first bug of this type being reported here, i think this is a problem with App Indicator on HiDPI displays.

**Comment by pshem** [comment] 2017-08-28 21:03
I have the same bug, on a 1024x768 screen in Peppermint 7(Ubuntu 16.04 based, the DE is XFCE with LXDE injections). No Wayland, let alone HiDPI

**Comment by spacekookie** [comment] 2017-08-28 21:19
@andyholmes No, I'm using X11 so I doubt that it has anything to do with a Wayland bug. Is there anything I can try to help debug this issue on my end?

**Comment by andyholmes** [comment] 2017-08-28 21:26
@spacekookie probably it's a Gtk or AppIndicator bug, one way or the other. If you could rerun indicator-kdeconnect, the panel app holding the indicators or whichever panel that is with `G_MESSAGES_DEBUG=all` you might get some useful info. Example:

```
killall -15 indicator-kdeconnect
G_MESSAGES_DEBUG=all indicator-kdeconnect
```

It might be more of a bug than error though, in which case you might not get an actual error message. If you don't, I would open a bug for Gtk on bugzilla.gnome.org and worst case they'll mark it as a duplicate of the bug you're looking for.

**Comment by MrMarukesu** [comment] 2017-09-11 20:55
maybe it's a icon problem, Adwaita uses 16px icons in scalable/status and the icons are now in 16px, 22px, 24px folders. i make a copy of the adwaita 16px icons here to hicolor scalable/status folder and there are in the same size of the others gnome icons.

**Comment by Bajoja** [comment] 2017-11-09 12:08
@spacekookie you solve the problem?

**Comment by spacekookie** [comment] 2017-11-09 13:17
@Bajoja Ah sorry, I'm not using cinnamon or your software anymore at the moment 😕 I'll try to re-create the issue and then get back to you, otherwise just close the issue for now I guess...

**Comment by Bajoja** [comment] 2017-11-10 00:45
@spacekookie no worry, :).

**Closed by Bajoja** 2017-11-10 00:45 UTC
