### ISSUE TITLE
"Browse device" not working

### ISSUE THREAD

**Issue by GoodGuyNick** [Bajoja/indicator-kdeconnect#10] opened 2016-12-05 16:07 UTC
I don't know whether the problem is in the sftp or in the indicator-kdeconnect.
When pressing "Browse device" it opens empty folder with 1TB free space. Path to the folder: /home/user/.config/kdeconnect/3eaf8b118bef4c06/kdeconnect_sftp/3eaf8b118bef4c06/
PC - Xubuntu 16.04.01, Smartphone - CM 12.1

Same issue was reported here: https://github.com/vikoadi/indicator-kdeconnect/issues/27

**Comment by Bajoja** [comment] 2016-12-05 17:41
@GoodGuyNick i think the problem is sftp, from nautilus based file manager, because  i test on dolphin and it work great. 
Nautilus only open sftp to android 4.4 and below.

**Comment by GoodGuyNick** [comment] 2016-12-05 17:46
I think it only works on dolphin, because I tested on pcmanfm, thunar and double commander.

**Comment by Bajoja** [comment] 2016-12-05 17:50
In this case we have to wait for some fix on sftp, or wharever the problem is.

**Comment by Bajoja** [comment] 2017-01-03 18:38
If someone know what the sftp problem or how to fix it, let me know.

**Comment by stibb** [comment] 2017-01-06 14:43
Same problem on elementary os 0.4

**Comment by tsjnachos117** [comment] 2017-01-14 03:16
Does this project use code from [Primitive FTP](https://github.com/wolpi/prim-ftpd)? I ask this because I've been having issues with Primative FTP (unable to browse my device), which I figure may or may not be related.

**Comment by Bajoja** [comment] 2017-01-14 23:08
@tsjnachos117 the SFTP is on KDEConnect level so i'm not sure what code they use but i think they use SFTP over SSH

**Comment by markcross** [comment] 2017-02-02 17:26
I'm on LXLE 16.04.1 Eclectica, I can only get the Browse Device to work this Dolphin as well.

Nautilus support would be cool, as I install that from DropBox support.

Nautilus seems to have sftp support but my phone doesn't seem to be exposing any ports which is quite right but how the hell does KDEconnect speak to it from the PC?!!

Oh well at least Dolphin works by copying and pasting the URL from the duff link in pcman and pasting into Dolphin

**Comment by tsjnachos117** [comment] 2017-02-02 21:40
@Bajoja Primitive FTP can use either FTP or SFTP. It comes pre-configured to do both, although I like to disable FTP.

@markcross I'm on Ubuntu 16.04.1, and I can't browser my Galaxy S6 at all, not even with Dolphin. Just out of curiosity, what happens if you use PCManFM to browse **~/.config/kdeconnect_sftp/(insert your phone's ID-thing here)/**?

**Comment by Bajoja** [comment] 2017-02-02 21:46
It's interesting how some people managed with androids higher than 4.4 in nautilus, I only get in nautilus with androids 4.4 and lower, does any android privacy policy is influencing?

**Comment by tsjnachos117** [comment] 2017-02-02 21:50
I don't use Nautilus, but I do use Nemo. I've only tried using this app on an Android 5.1 device. I do have an old Android 4.x phone (I can't remember which version of Android it runs), so maybe I'll try using that. I'll also try on my CyannogenMod Tablet, which runs CM 12.1 (which is based on Android 5.1). Maybe CM will do have different results than regular Android.

**Comment by tsjnachos117** [comment] 2017-02-02 22:07
Hmm... I get the same results on all of my devices. My Galaxy S6 (Android 5.1) with stock firmware, my Razr HD with root (Android 4.1.2), and my tablet (Cyanogenmod 12.1) all refuse to let me browse the device.

**Comment by Bajoja** [comment] 2017-02-03 00:30
Oh my god this is more serious than i imagined ...

**Comment by tsjnachos117** [comment] 2017-02-03 00:38
IDK if this holds any relevance, but I should mention I only tested Dolphin with my S6. On my other devices, I only used Nemo.

If it's any consolation, everything else KDE Connect is supposed to do seems to work perfectly well.

**Comment by markcross** [comment] 2017-02-03 10:56
@tsjnachos117 

> what happens if you use PCManFM to browse ~/.config/kdeconnect/(insert your device's ID-thing here)/kdeconnect_sftp/(your device's ID-thing again)/?

I just get a blank window with no file / folder listing

![screenshot from 2017-02-03 10-55-36](https://cloud.githubusercontent.com/assets/768391/22588804/5e6a27de-e9ff-11e6-9a62-654c926b1c5d.png)

**Comment by Bajoja** [comment] 2017-02-03 14:29
The Android 4.4 that I test and work, is a Huawei to.

**Comment by anthonytex** [comment] 2017-02-08 21:21
Hi all for those who have problem with phone browsing: make sure to have installed sshfs that should be an optional dependency for both kdeconnect and openSSH. Without it it's impossible to browse your device becouse KC is based on sshfs for remote browsing according to its source.

**Comment by Bajoja** [comment] 2017-02-08 22:04
I install both but still not working

**Comment by tsjnachos117** [comment] 2017-02-08 22:29
Same here. I've been using sshfs to transfer files between computers since before I had even heard of KDE Connect (I also sometimes use scp, but mounting a remote directory often makes file transfers more convenient).

I do have a theory: maybe KDE Connect tries to remotely access the wrong folder. On my device, /sdcard works well with Primitive FTP, but the directories inside /storage do not. If KDE Connect also uses something in /storage, maybe that's the problem. I'll bet sime Android distros (I don't like calling them "ROMs") handle /storage partitions differently than others. I f so, that could explain why KC's file browsing works on your Android 4.4 Huawei device while refusing to work on mine: your system handles partitions differently then mine.

**Comment by anthonytex** [comment] 2017-02-09 12:21
I'm sorry guys i hoped it would have been so simple: by the way i'm using it on Arch plus nemo and it's working good with android 7.

**Comment by Bajoja** [comment] 2017-02-09 13:45
Mk

**Comment by anthonytex** [comment] 2017-02-09 14:05
I've tested it with a Oneplus 3 and on nexus 5x the first with Archlinux with nemo file manager the second, on another machine, with Archlinux and mate desktop (compiled with gtk3 to be clear) that should use caja (?) : both are working fine.
Archlinux's kdeconnect package has this dependencies:
> hicolor-icon-theme
kcmutils
kwayland
libfakekey
qca-qt5
kde-cli-tools (optional) - configuration UI
sshfs (optional) - remote filesystem browser
extra-cmake-modules (make)
kdoctools (make)
python (make)

which distro are you using?

**Comment by Bajoja** [comment] 2017-02-09 14:57
I use Fedora 25 with Gnome, so Nautilus as file manager

**Comment by anthonytex** [comment] 2017-02-09 15:19
Well the only different with kdeconnect on arch and fedora ( speaking of dependencies) is kwayland that is called "kf5-kwayland" am i wrong?
(and maybe this hicolor-icon-theme)

**Comment by tsjnachos117** [comment] 2017-02-09 19:30
I'm using Ubuntu 16.04. I have the 64-bit version installed, which may be a factor. I have one machine running Arch, but I can't use it for more than 2-3 minuets (barely long enough to boot) before it freezes and/or kernel panics (video driver bug), so I can't test KDE Connect until the bug gets resolved.

**Comment by anthonytex** [comment] 2017-02-09 22:31
Just downloaded Ubuntu live 16.10: for me it's working also here. Well have you try directly with kde? Just for test what happens there? I'm not able to reproduce this bug. I will try with other phones on the next days.

**Comment by Bajoja** [comment] 2017-02-10 02:49
I will test Ubuntu 16.10 too.

**Comment by TdsMG** [comment] 2017-02-11 21:52
I've experienced the same problem on my computer (Ubuntu 16.04, Android 6.0). Please feel free to request any log or file that may be useful to identify the bug.

**Comment by Moondownr** [comment] 2017-02-16 08:52
Xubuntu 16.04, Thunar, same problem (empty folder opens).

**Comment by anthonytex** [comment] 2017-02-16 09:02
I suggest you to add also informations about devices and Android versions
that are afflicted by this problem to be more clear :)

Il 16 feb 2017 9:52 AM, "Moondownr" <notifications@github.com> ha scritto:

**Comment by jlopezay** [comment] 2017-02-18 13:02
I have changed form Kubuntu 16.10 to Linux Mint Cinnamon 18 last week.
Kdeconnect was working ok in Kubuntu with Dolphin. Actually, with Linux Mint and the same Android device I have an empty folder  using Nemo.

Device: Bq Aquaris M5
Android version: 6.0.1

**Comment by tsjnachos117** [comment] 2017-02-20 21:05
I've got Arch working, and have tried kde-connect using the AUR mentioned on the project's front page (or whatever you call it... README.md). I have no file browsing on Arch, either. I'm running the Cinnamon Desktop, which might be a factor. I'll try with KDE when I can.

**Comment by tsjnachos117** [comment] 2017-02-21 01:29
Nope, not working on Arch with Plasma 5, either. I've got an empty folder, as per usual. I did get a rather interesting error when I clicked KDEConnect's file browser icon: `A folder named /home/[my user]/.cache/kioexec/krun/[12345]_0/ already exists`. The "[12345]" at the end changed everytime I clicked the icon, but the name always ended with "_0". I tried running `rm -rf ~/.cache/kioexec`, but that didn't make any difference.

Shortly after, I realized that I wasn't clicking on the indicator, but rather some kind of systray icon. When I tried with indicator-kde, I didn't get any error messages, although my device was still inaccessible.

When I tried to manually browse my device, Dolphin gave me the following error: `The file or folder /home/[my user]/.config/kdeconnect/[my device id]/kdeconnect_sftp/[my device id]/storage/emulated/0 does not exist.`, which means the problem is the probably usage of `/storage/emulated/0`. On my particular Android (I don't like using the term "ROM"), `/sdcard` usually works best. However, when I tried to manually browse `/home/[my user]/.config/kdeconnect/[my device id]/kdeconnect_sftp/[my device id]/sdcard`, Dolphin game me the same "does not exist" error as when I tried to browse `/home/[blablabla, you get the idea]/storage/emulated/0`.

**Comment by antigone2** [comment] 2017-02-22 16:55
Same here 16.10, empty folder. Also SMS send not working. And if you have launcher set for hiding, browsing via remote input won't show it up.

**Comment by Bajoja** [comment] 2017-02-23 00:38
@antigone2, Why SMS send not working?
Need more information.

**Comment by tsjnachos117** [comment] 2017-02-25 02:05
I just downloaded a brand new version of KDE Connect from F-Droid. File browsing is working on 2 different machines!

@antigone2: I've found that it sometimes takes a minute or two for the phone to send the message. On one occasion, I though sending an SMS had failed, causing me to retry a few times. After a few seconds, I gave up, started sending the message via my phone... and just like that each "failed" attempt went through, confusing the person I was talking to.

If the message doesn't go through after maybe 60 seconds, make sure KDE Connect is running on your phone. If your phone has been locked recently, KDE Connect may have been suspended* automatically by your phone. According to [this other issue](https://github.com/Bajoja/indicator-kdeconnect/issues/43), there's not much the developer can do, although you may - depending on your Android distro - be able to disable auto-suspending apps, though doing so may lower your battery life.

*that is, your phone has temporarily frozen the app to save power.

**Comment by antigone2** [comment] 2017-02-25 07:28
Well, now I am actually unable to launch indicator-kdeconnect, even after purging and reinstalling, so problem "solved". For the lack of time I am at the moment unable to look to it more, but if I found something I would let know.

**Comment by Bajoja** [comment] 2017-02-25 16:46
@tsjnachos117 what is the version of kdeconnect you download? The last version on PlayStore os 1.6.1

**Comment by tsjnachos117** [comment] 2017-02-25 19:31
What do you mean by "PlayStore os"? Are you refering to Google Play?

I'm running 1.6.1 from F-Droid.

**Comment by Bajoja** [comment] 2017-02-25 19:54
@tsjnachos117 i'm sorry, I wanted to write "Play Store is"

**Comment by jlopezay** [comment] 2017-03-01 16:27
Hi again,

I been making more tests. Using other two android devices I can browse the files without problems, but I still have a empty folder when i try to browse my Bq phone.

I have tried with another computer (kubuntu) and my Bq phone and all is working correctly.

I don't know what more should try. Could somebody, please, give some advise?

Kind Regards.

**Comment by marioaria** [comment] 2017-04-16 13:18
Same issue on Ubuntu 16.04 with MATE desktop. Phone is Sony Xperia Z3.

**Comment by dmarcostx** [comment] 2017-04-16 15:08
### Test
**Computer**: kdeconnect 1.0.3-0neon+16.04+build23 on KDE neon 5.9
More information about computer: sshfs 2.5-1ubuntu1, dolphin 4:16.12.3-0neon+16.04+build22, Linux kernel version 4.8.0-48-generic 64 bits and indicator-kdeconnect not installed
**Phone**: kdeconnect 1.6.1 _latest avalible_ from Goole Play on Xiaomi Redmi 2 Pro with MIUI _latest avalible_ Global Stable 8.2.1.0 (LHJMIDL) on Android 5.1.1 LMY47V

**Tested**: Browse device
**Test result**: Not working
Test error: /home/marcos/.config/kdeconnect/7f0004561a6f65b1/kdeconnect_sftp/7f0004561a6f65b1/storage/emulated/0 does not exist

**Comment by tsjnachos117** [comment] 2017-04-18 20:48
I have been having some trouble on and off with this feature. However, I've found the some troubleshooting steps that usually work quite well. Here are the steps I use, in no particular order:

1. Make sure your phone/tablet is connected to the same WiFi network as your desktop/laptop.

2. Open kdeconnect on your Android homescreen. This may seem like an unnecessary step, but I think Android periodically kills background processes it deems "unnecessary", so re-opening kdeconnect can help in that regard.

3. Go into your Android device's settings, select Applications, and find kdeconnect. Tap the "Force Stop" button. Then manually re-open the app.

4. Kill kdeconnect on your PC. You can do this from the terminal by typing `pkill -x indicator-kdeco; pkill -x kdeconnectd`. Then re-open indicator-kdeconnect using your desktop environment's application menu.

5. Make sure your firewall is configured to allow kdeconnect to use ports 1714-1764 for input and output. kdeconnect uses both TCP and UDP.

If non of the above works, I guess more work needs to be done to fix this bug.

**Comment by Bajoja** [comment] 2017-04-18 21:14
@tsjnachos117 don't work on nautilus.
It's a temporary? like when you restart your computer you have to do this all again?

**Comment by tsjnachos117** [comment] 2017-04-18 21:41
My issues don't happen too often. When they do occur, I don't even bother to reboot any of my devices, since the above steps are faster, and 100% effective (in my case at least).

Of course, I still can't access /storage, but that's not an issue for me. It might prove to be an issue for others, though.

**Comment by pank** [comment] 2017-04-26 09:51
I can't browse the content of my phone either for what it is worth.  I'm using
- Sony Z3 (with Gapps removed)
- The F-Droid version of KDE Connect
- The AUR version of `indicator-kdeconnect` (I have got `sshfs` installed).
I have funny things in the `journalctl` like this

```
Apr 26 11:46:09 W530 systemd[1]: Timed out waiting for device dev-disk-by\x2duuid-fd380b39\x2da7b3\x2d490c\x2d8939\x2d7b40ceadaddd.device.
Apr 26 11:46:09 W530 systemd[1]: Dependency failed for /media/extra_data.
Apr 26 11:46:09 W530 systemd[1]: media-extra_data.mount: Job media-extra_data.mount/start failed with result 'dependency'.
Apr 26 11:46:09 W530 systemd[1]: dev-disk-by\x2duuid-fd380b39\x2da7b3\x2d490c\x2d8939\x2d7b40ceadaddd.device: Job dev-disk-by\x2duuid-fd380b39\x2da7b3\x2d490c\x2d8939\x2d7b40ceadaddd.device/start failed with res
Apr 26 11:46:09 W530 systemd[1]: dev-disk-by\x2duuid-677c252d\x2d9498\x2d4a7a\x2d8f91\x2d333a47e094c6.device: Job dev-disk-by\x2duuid-677c252d\x2d9498\x2d4a7a\x2d8f91\x2d333a47e094c6.device/start timed out.
Apr 26 11:46:09 W530 systemd[1]: Timed out waiting for device dev-disk-by\x2duuid-677c252d\x2d9498\x2d4a7a\x2d8f91\x2d333a47e094c6.device.
Apr 26 11:46:09 W530 systemd[1]: Dependency failed for /media/external_data.
Apr 26 11:46:09 W530 systemd[1]: media-external_data.mount: Job media-external_data.mount/start failed with result 'dependency'.
```

Also, when I click `Send SMS` nothing happens.  The error seems to be this
```
Apr 26 11:51:04 W530 indicator-kdeco[4178]: DeviceIndicator.vala:132: Failed to execute child process “/usr/share/indicator-kdeconnect/Sms.py” (Permission denied)
```

**Comment by Bajoja** [comment] 2017-04-26 13:54
@pank the SMS execution problem is fixed on this commit 4dfbedf, please don't post different bugs on a bug.

**Comment by KycokCkpunta** [comment] 2017-05-14 11:09
When i'm click "Browse device", there are popping error message from audacious (!) "No files found"
I have Gnome, sshfs, and other deps installed

**Comment by getmeacuboftea** [comment] 2017-05-19 16:51
I have the same problem when using the browse device feature, nemo file manager.
When i try to access folder (ls command)
~/.config/kdeconnect/2171a4a07e1ff93f/kdeconnect_sftp/2171a4a07e1ff93f 
and
~/.config/kdeconnect/2171a4a07e1ff93f/kdeconnect_sftp/2171a4a07e1ff93f/storage/self
it give the Permission deny error, but when i try folder
~/.config/kdeconnect/2171a4a07e1ff93f/kdeconnect_sftp/2171a4a07e1ff93f/storage
and 
~/.config/kdeconnect/2171a4a07e1ff93f/kdeconnect_sftp/2171a4a07e1ff93f/storage/self/primary
everything work properly.
I guess it's a permission problem on Android 6.0, i have the same problem with file manager on Android when i can't open /storage/self but /storage/self/primary open properly.
Dolphin/kde work properly without any problem.

**Comment by Bajoja** [comment] 2017-05-19 18:07
For all the people here who want to test something on ![dev branch](https://github.com/Bajoja/indicator-kdeconnect/tree/dev) where i have a working version of this. 
You should go to indicator-kdeconnect-settings and active the option "Show device directories"
![captura de ecra de 2017-05-19 18-57-04](https://cloud.githubusercontent.com/assets/10621831/26260766/610d362e-3cc6-11e7-929f-9d16ebff5810.png)

**Comment by getmeacuboftea** [comment] 2017-05-20 05:22
Thank you very much, dev version solve that problems for me.

**Comment by Bajoja** [comment] 2017-05-21 16:59
@getmeacuboftea the browse "SD Card" work for you?

**Comment by FinderX** [comment] 2017-06-14 01:40
Work for me if I adding "sdcard" on the end of the path.

~/.config/kdeconnect/98b2ce4882427226/kdeconnect_sftp/98b2ce4882427226/sdcard

I can read and write without problem.

But open default "Browse Device" open a blank folder

~/.config/kdeconnect/98b2ce4882427226/kdeconnect_sftp/98b2ce4882427226/

Using Linux Mint 18.1, Nemo FM, Samsung Galaxy S7, Android 7.0 stock rom and last KdeConnect 1.6.4
I don't know if is checked "Device Reachable and Trusted" help with this problem.

**Comment by jlopezay** [comment] 2017-06-14 06:01
Thanks FinderX, 

I have up some months ago :) 

Just adding /sdcard at the end of the path also works for me.

**Comment by bgeVam** [comment] 2017-06-25 14:52
@Bajoja I always need to manually select "browse device" before I am able to access my device. Is there a reason the sshfs connection isn't already established when the indicator starts and the "browse device" option only opens the folder in the file browser?

**Comment by MarkoIndaco** [comment] 2017-10-09 16:40
Guys I really goin mad with this. Lemme explain better: Got 2 devices, the old Sony Xperia E4g (KitKat 4.4.4) works like a charm, instead the new HTC One M9 (Nougat 7.0) show and empty folder. I already try to:
- delete the **kdeconnect** folder
- disassociate both the devices
- associate each others (tested and working, they transfert files each other as well)

Plus: All others Kde-Indicator functions on HTC works fine as **Send file**, **Finde my phone** etc.
@FinderX can you please explain more detailed how did you rename/add **sdcard** path?
When I try to do that, with **root* priviliges, it show an error

**Comment by jlopezay** [comment] 2017-10-09 17:22
Marko,

In my case, when I select Browse device, the file browser opens the
following blank folder:

/home/jose/.config/kdeconnect/e221a4d89b0aecc6/kdeconnect_sftp/e221a4d89b0aecc6

then I just edit the path adding manually the /sdcard

/home/jose/.config/kdeconnect/e221a4d89b0aecc6/kdeconnect_sftp/e221a4d89b0aecc6/sdcard
and works

Kind Regards.

2017-10-09 18:40 GMT+02:00 Marko <notifications@github.com>:

**Comment by CodeSeba** [comment] 2017-10-09 18:46
@MarkoIndaco Just exactly like @jlopezay say in his post. I give this screenshots for illustrations.

![peek 2017-10-09 15-40](https://user-images.githubusercontent.com/31450548/31353395-d7131d22-ad08-11e7-8765-12b7f28de594.gif)

Regards.

**Comment by MarkoIndaco** [comment] 2017-10-09 23:36
Thank you guys for explanations and video. Indeed (because I'm noob) my **address bar** was hidden by settings. Unluckly, even enabling the address bar and adding the sdcard at the end of the address, I got en error (see screenshot). It's write in italian but maybe you understand what's the problem.
I also try to attach the **/sdcard** opening the **Home** folder, but got the same error.

![github - kdeconnect issue 1](https://user-images.githubusercontent.com/19596617/31362912-5934f436-ad5b-11e7-8b37-459545c62880.png)

**Comment by tsjnachos117** [comment] 2017-10-10 01:52
Instead of adding "/sdcard", you can try adding "/storage" or "/mnt". The former works best on my Galaxy Tab 2 7.0 (LineageOS 13), and the latter works best on my Galaxy S6 (Android 5.1).

**Comment by MarkoIndaco** [comment] 2017-10-10 02:12
Thank very much mate. Following you're suggestion I find the way. I try to add **/storage** and it shows me 3 folder. Following this way I try **/mnt** instead, and this shows the folders where I find (also) the sdcard. Find this was simple to understand that I shuold attach **/mnt/sdcard** to access to the external storage. :+1: 

Thank you again **all** for help and support!

**Comment by C0rn3j** [comment] 2017-11-02 09:57
Am on Arch Linux - doesn't work on Nautilus, works on Dolphin. 

Had to install sshfs (unsurprisinigly).

**Comment by tsjnachos117** [comment] 2017-11-03 03:04
@C0rn3j Can you mount the device through the applet and manually browse any directories in `~/.config/kdeconnect/` with Nautilus? Can you browse said directories from the shell?

**Comment by andyholmes** [comment] 2017-11-03 03:14
Be aware KDE Connect sftp server has issues with SSHFS 3.x, and I believe Arch uses 3.3 currently.

https://github.com/KDE/kdeconnect-android/blob/master/src/org/kde/kdeconnect/Plugins/SftpPlugin/SimpleSftpServer.java#L230

**Comment by C0rn3j** [comment] 2017-11-03 07:06
@andyholmes  Arch is on 3.3.1, the comment you linked specifically mentions 3.0 and 3.2.

@tsjnachos117 ```
c0rn3j@Thor : ~/.config/kdeconnect
[0] % ls -lah *  
-rw------- 1 c0rn3j c0rn3j 1.2K Nov  2 10:39 certificate.pem
-rw------- 1 c0rn3j c0rn3j 1.7K Nov  2 10:39 privateKey.pem
-rw-r--r-- 1 c0rn3j c0rn3j 1.2K Nov  2 10:45 trusted_devices

4e735b0eee347175:
total 4.0K
drwxr-xr-x 1 c0rn3j c0rn3j  96 Nov  2 16:57 .
drwxr-xr-x 1 c0rn3j c0rn3j 120 Nov  2 10:45 ..
-rw------- 1 c0rn3j c0rn3j 524 Nov  2 10:45 config
drwxr-xr-x 1 c0rn3j c0rn3j   0 Nov  2 16:57 kdeconnect_pausemusic
drwxr-xr-x 1 c0rn3j c0rn3j   0 Nov  2 10:40 kdeconnect_runcommand

c0rn3j@Thor : ~/.config/kdeconnect
[0] % ls -lah ./*/*
-rw------- 1 c0rn3j c0rn3j 524 Nov  2 10:45 ./4e735b0eee347175/config

./4e735b0eee347175/kdeconnect_pausemusic:
total 0
drwxr-xr-x 1 c0rn3j c0rn3j  0 Nov  2 16:57 .
drwxr-xr-x 1 c0rn3j c0rn3j 96 Nov  2 16:57 ..

./4e735b0eee347175/kdeconnect_runcommand:
total 0
drwxr-xr-x 1 c0rn3j c0rn3j  0 Nov  2 10:40 .
drwxr-xr-x 1 c0rn3j c0rn3j 96 Nov  2 16:57 ..
```
Using the applet gives me this error message, and the folder structure then looks like this, so no.

```A folder named /home/c0rn3j/.cache/kioexec/krun/2979_0/ already exists.```

**Comment by ArchangeGabriel** [comment] 2017-11-03 08:50
I also have this error message. See https://bugs.kde.org/show_bug.cgi?id=373967.

Apparently this is an error with kio.

Also, I had problem before with kdeconnect and sshfs because of hardening I made in /etc/ssh/ssh_config.

**Comment by andyholmes** [comment] 2017-11-03 17:10
@C0rn3j You may be right it was fixed in 3.3 (probably best to check), but the commit says:

> Detect data corruption caused by sshfs 3.x and abort transfer

If you get a message say something to the effect of "Connection reset by peer", then the Android app has decided (for some reason) to close the connection. If you don't have `fusermount` installed kdeconnect tries to use `umount` which doesn't work as reliably. Additionally, it may fail to cleanly unmount if the directory is in use when it tries.

> [//Free mount point (won't always succeed if the path is in use)](https://github.com/KDE/kdeconnect-kde/blob/master/plugins/sftp/mounter.cpp#L238)

For me, sshfs always chokes in the top-level directory when listing files, which I think is a know issue with SSHFS/SFTP. I have to use a directory under it like `DCIM` or `Download`.

**Comment by tsjnachos117** [comment] 2017-11-03 22:49
@C0rn3j AFAIK, the indicator doesn't use KIO, it's odd that the error message you got mentions "kioexec". Also, the indicator mounts to `~/.config/kdeconnect/[device-id-thinggy]/kdeconnect_sftp/[device-id-thnggy agan]`. (It looks to me like your device-id-thinggy is "4e735b0eee347175".)

Perhaps the indicator uses different mount points than KDE? If so, maybe the problem is that KDE already mounted the device, and the indicator refuses to mount it because it's already mounted in a subdirectory of ~/.cache?

I would try checking for any mounted sshfs shares, and unmounting all of them, unless you have some shares you need to access. You can then try mounting with the indicator (perhaps you should close Dolphin first, and maybe test with some desktop other than KDE), and do `ls ~/.config/kdeconnect/4e735b0eee347175/kdeconnect_sftp/4e735b0eee347175/storage`. I included the "/storage" directory because some Android systems don't seem to like to show their root directories, although Android should let you browse certain subdirectories, such as /storage or /mnt.

**Comment by andyholmes** [comment] 2017-11-03 23:12
@tsjnachos117 You're right, KDE Connect [stopped using kio](https://github.com/KDE/kdeconnect-kde/blob/master/plugins/sftp/mounter.cpp#L86-L98) sometime ago for this and probably couldn't anymore because of bug [#351725](https://bugs.kde.org/show_bug.cgi?id=351725), unless KIO allows some pretty advanced configuration of SFTP. The only thing it use KIO for now is to add the device to the Places area in Dolphin.

On the other hand, the indicator doesn't do any mounting at all, it just asks KDE Connect to do it via DBus. You could be right about unmounted (or uncleanly unmounted) sshfs share hanging around, probably these would show up in `mount`.

**Comment by ArchangeGabriel** [comment] 2017-11-03 23:23
Hum indeed. I have a line in mount:
```
kdeconnect@IP:/ on /run/user/1000/<hexaid> type fuse.sshfs (rw,nosuid,nodev,relatime,user_id=<user_id>,group_id=<group_id>)
```

**Comment by ArchangeGabriel** [comment] 2017-11-03 23:25
But permissions…
```
d????????? ? ?        ?          ?              ? <hexaid>
```

**Comment by C0rn3j** [comment] 2017-11-04 09:28
@tsjnachos117 
>You can then try mounting with the indicator (perhaps you should close Dolphin first, and maybe test with some desktop other than KDE),

My DE is Cinnamon and I primarily use Nautilus. I just used KDE for testing and before I couldn't really find anything.

I've tried multiple times even after rebooting.

**Comment by Bajoja** [comment] 2017-11-06 23:23
I use Arch Linux, sometimes it work, sometimes not.
@andyholmes what you use in the extension to mount the file system, the DBus command?

**Comment by andyholmes** [comment] 2017-11-06 23:33
@Bajoja Yep, I use `mountAndWait()` then I call `getDirectories()` that returns the directory/name pairs and that's what I show in the menu. For me the top directory always causes sshfs to disconnect while listing files though, so I use the Camera directory. I think the Android app uses some built-in SFTP server class that's not very good.

**Comment by andyholmes** [comment] 2017-11-07 00:04
If this works in Dolphin, it must be a Nautilus problem, maybe the way it lists directories over SSHFS. I thought maybe the server class in the Android app had changed, but I don't this it has. In my newer extension I do it almost exactly how KDE Connect does and I still get crashes in the top-level directory.

https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/master/src/service/plugins/sftp.js#L127
https://github.com/KDE/kdeconnect-kde/blob/master/plugins/sftp/mounter.cpp#L124

**Comment by Bajoja** [comment] 2017-11-09 01:36
@andyholmes by that solve the problem, i will launch a new version with the browse of the paths get it from the Dbus method get directory, it will be optional and it can be enabled on settings.

**Comment by Bajoja** [comment] 2017-11-10 00:43
The last commit should solve the problem, just compile and install it, then go to settings and enable the option to show directories instead of broswe device and voilá.

**Closed** 2017-12-24 18:47 UTC
Labels: help wanted, question

**Comment by bhughesshelton** [comment] 2018-09-14 17:16
I am experiencing this issue on Manjaro with Plasma, trying to connect to a Galaxy S5 with Google Android, but only when Thunar is set as the default file manager (i.e. If I set Plasma to prefer Dolphin, all works as it should). Each attempt to connect to the device creates a new directory and throws an error 'A folder named /home/user/.cache/kioexec/krun/randomNum/ already exists.' that the directory already exists. I am able to send data back and forth over CLI, notifications work properly, etc.

**Comment by xgdgsc** [comment] 2018-11-15 08:21
Not working for me on Kubuntu 18.04 with xiaomi 8 after clicking "All FIles", shows `The file or folder does not exist.`

**Comment by swedneck** [comment] 2018-11-19 13:42
I get a message saying that /home/user/.cache/kioexec/krun/32199_0/ already exists when i try to browse my phone, my phone also doesn't show up in thunar.

**Comment by ArchangeGabriel** [comment] 2018-11-19 13:52
Apparently this feature only works with Nautilus…

**Comment by bastafidli** [comment] 2018-11-23 04:08
> Not working for me on Kubuntu 18.04 with xiaomi 8 after clicking "All FIles", shows `The file or folder does not exist.`

On ubuntu 18.04 adding backports ppa and upgrading to kde connect 1.3.3 solved the problem

**Comment by freddii** [comment] 2018-12-03 19:20
Rolling  back to  KDE Connect 1.8.4 from F-droid fixed it.

**Comment by alexanderadam** [comment] 2018-12-19 07:37
Could it be related to [this issue from 2015](https://bugs.kde.org/show_bug.cgi?id=351725)?

**Comment by C0rn3j** [comment] 2019-01-20 22:04
I have the same issue I had when I initially posted here in 2017.

I am on Arch, running kdeconnect 1.3.3 and on LineageOS I am running 1.10.1.

I can open the device fine in Dolphin directly:

![image](https://user-images.githubusercontent.com/1641362/51445613-9e572a80-1d07-11e9-9138-1e96e0afd87c.png)

However if I try to open it through  the tray via right click > devicename > Browse  files I get this error:

![image](https://user-images.githubusercontent.com/1641362/51445618-b038cd80-1d07-11e9-9c86-b7874a119fc8.png)

**Comment by ArchangeGabriel** [comment] 2019-01-20 22:05
@C0rn3j Is Dolphin your only/default file browser?

**Comment by C0rn3j** [comment] 2019-01-20 22:06
Neither only or default, default  is Nautilus

**Comment by ArchangeGabriel** [comment] 2019-01-20 22:07
Then that’s your issue. Only Dolphin works with KDE Connect.

**Comment by C0rn3j** [comment] 2019-01-20 22:08
If that is true then kdeconnect should make that button open Dolphin, not try whatever is the default file manager only to throw an error.

**Comment by ArchangeGabriel** [comment] 2019-01-20 22:10
Well, more importantly KDE Connect should be made working with other files browsers. But anyway, this is not the right place for this.

**Comment by tsjnachos117** [comment] 2019-01-21 02:01
Actually, I think that Dolphin (or kio) might be interfering. kdeconnect 1.3.3 should mount to `/run/user/(user id number)/*`, not `~/.cache/kioexec/krun/*`. Try this: `fusermount -u ~/.cache/kioexec/krun/*`, and then try mounting again.

**Comment by C0rn3j** [comment] 2019-01-21 08:00
```
[1] % fusermount -u ~/.cache/kioexec/krun/*
fusermount: extra arguments after the mountpoint
```

**Comment by tsjnachos117** [comment] 2019-01-21 23:36
What is the output of `mount | grep -e ssh`? Likewise for `mount | grep fuse`?

**Comment by dylskiMarcin** [comment] 2019-02-25 22:24
Hi @tsjnachos117, I have the same problem as C0rn3j.
I'm using **Manjaro** with **Cinnamon 4.0.9** and **Deepin** as default file manager.

**$ mount | grep -e ssh**
`kdeconnect@[--IP--]:/ on /run/user/1000/9193b7e04a70e48 type fuse.sshfs (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)`

**$ mount | grep fuse**
`fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
kdeconnect@[--IP--]:/ on /run/user/1000/9193b7e04a70e48 type fuse.sshfs (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
`

There directory **/run/user/1000/9193b7e04a70e48/** is present but not accessible. 

Bellow I attach gist with kdeinit5 output after "KDE Connect -> Browse device"
https://gist.github.com/dylskiMarcin/034b7e6446d15449357215bd0f18fcc1

**Comment by ArchangeGabriel** [comment] 2019-03-25 15:49
kdeconnect 1.3.4 which was just released seems to finally fix this issue according to the changelog:
> * [kio] Fix file browsing with non-KIO file managers

I should be able to confirm soon. :)

**Comment by eriefisher** [comment] 2019-04-27 21:27
Just installed 1.3.4 from Ubuntu on my antix with xfce system. kdeconnect now goes farther but when trying to browse device it open the text editor instead of thunar. I need to find an open with config or some way to tell it to open thunar. The previous version would fail as mentioned earlier but navigating to the mount path pulled from mtab would work. Just a lot of work to see files.

Anyone know how to change the open with parameters?
![kdeconnect](https://user-images.githubusercontent.com/567829/56855224-babfc000-6911-11e9-8ee5-2eabeb4d3b46.jpg)

**Comment by tp0** [comment] 2019-05-03 06:35
@eriefisher 
Copy/type that location in that dialog into Thunar's location bar (Ctrl+L) and then add it as a bookmark.

**Comment by eriefisher** [comment] 2019-05-04 19:53
Yes, thank you. I know I can navigate/bookmark. Everything is accessible, just not through the application. Does this thing work properly with KDE?

**Comment by awsms** [comment] 2020-03-24 18:33
While trying to browse my device, using the "Browse device" button on the indicator:

```
A folder named /home/user/.cache/kioexec/krun/14868_0/ already exists.
```

Wut? Lol
