### ISSUE TITLE
Paired Laptop/Desktop breaks Nemo/Nautilus extension

### ISSUE THREAD

**Issue by szekeres2016** [Bajoja/indicator-kdeconnect#47] opened 2017-03-18 09:51 UTC
Good day, I love this application so far. I noticed some strange behavior though. On the KDE connect settings panel my laptop is showing up along my phone, and on the laptop the desktop pc is visible. If I pair them they work fine I can send files etc with the tray menu, but by pairing the desktop and laptop the "Send KDE connect" option disappears from the Nemo/Nautilus menu. I also noticed that despite the phone is connected via Wi-Fi it isn't connected to Linux unless I click a button on it. I'm not sure if this is a bug in the Android app or whatever but since it does not connect the phone functions like "find my phone" is useless because I first have to find the phone and click a button and then it connects successfully. Anyway if there is a way to simply hide the desktop/laptop from showing up in the list that would do the trick for not breaking the file manager extension as well.

EDIT: I paired my android tablet as well, in the KDE Connect send-to menu only my phone or my tablet is visible not booth at the same time. If my desktop or laptop is connected then the menu is gone altogether. If I suspend the linux machine or turn it off the KDE Connect send-to menu is back so the extention is definitely working and not crashing out it just gets removed in the case of a connected paired linux machine.

**Comment by Bajoja** [comment] 2017-03-18 18:16
I @szekeres2016 
1º - See #43 for more information about why your phone disappear sometimes, it's about your phone power manager;

2º -  I've never noticed that when a desktop is connected to the laptop the "kdeconnect-send nautilus" disappears. I will investigate more about that, but if you have any log or something like that post here.

**Comment by szekeres2016** [comment] 2017-03-19 13:56
How can I find relevant logs for this case?

**Comment by szekeres2016** [comment] 2017-03-20 17:41
On a related note, the Nautilus extension makes the file manager hang several seconds after I use Ctrl+X or Ctrl+V. It becomes unresponsive and will grey out for a few seconds (it will not crash) but it makes the user experience quite unpolished. Is there a way to disable the file manger extension? I only see option for it Nemo (but Nemo is unaffected by this bug).

**Comment by Bajoja** [comment] 2017-03-20 19:36
@szekeres2016 
See #46 to remove kdeconnect-send-nautilus and use kdeconnect-send scritp, until we found a solution for this bug

**Comment by Bajoja** [comment] 2017-03-22 03:05
Nautilus freeze problem freeze it's fixed now on #33be5e7

**Comment by szekeres2016** [comment] 2017-03-22 06:46
I've downloaded the updated "kdeconnect-send-nautilus.py" and placed it in "/usr/share/nautilus-python/extensions" and rebooted. The copy and paste action hangs are gone, but the right click menu now doesn't update properly, only one device is showing and to force it to update I have to pkill nautilus and restart. If laptop is connected with the desktop the KDE Connect send-to menu is gone, so that seems to be buggy.

**Comment by Bajoja** [comment] 2017-03-22 12:31
@szekeres2016, Umh, maybe the problem is the regular expression that detect device id it not detect underscores, can you confirm for me what character's your laptop or desktop id have, you cand found running on cmd the command "kdeconnect-cli -l", but before that ensure they are paired.

**Comment by szekeres2016** [comment] 2017-03-22 14:36
I had an idea something like that can be a cause for this, so the first thing I've done was to rename all my devices based on the simple rule I use to name my devices for Wi-Fi and Bluetooth connect. My phone is 'PETER-PHONE', tablet is 'PETER-TABLET' laptop and desktops are 'PETER-LAPTOP' and 'PETER-DESKTOP' respectively.

**Comment by Bajoja** [comment] 2017-03-22 15:03
@szekeres2016 Ok, run the cmd command "kdeconnect-cli -l" and put the output here please

**Comment by szekeres2016** [comment] 2017-03-22 15:07
**When run on desktop with Linux Mint 18.1 Cinnamon 64-bit:**
peter@peter-desktop ~ $ kdeconnect-cli -l
- PETER-TABLET: 42a43a78b8e6abc7 (paired and reachable)
- PETER-PHONE: 5249b0111fee34e4 (paired and reachable)
- PETER-LAPTOP: _562cb2ad_6bb6_45a9_af72_ee40ba45ba43_ (paired and reachable)
3 devices found

**When run on laptop with Ubuntu 16.04.2 LTS 64-bit:**
peter@peter-laptop:~$ kdeconnect-cli -l
- PETER-TABLET: 42a43a78b8e6abc7 (paired and reachable)
- PETER-PHONE: 5249b0111fee34e4 (paired and reachable)
- PETER-DESKTOP: _6c77b709_96d9_4f5f_8b47_69714bfa6e19_ (paired and reachable)
3 devices found

**Comment by Bajoja** [comment] 2017-03-23 22:37
@szekeres2016 check the new commit, everthing should work now, but you have to compile the source code, beacause i change the way that the info is passed to kdeconnect-send-nautilus.py.

Give a feedback to launch a new release and correct this bug.

**Comment by szekeres2016** [comment] 2017-03-24 06:22
@Bajoja I removed the current one I've installed from ppa, but I can't go on about compiling it from source. I'm stuck at installing the dependencies, ubuntu will not allow me to install libgtk-3-dev and libappindicator3-dev because unmet dependency error. :S

**Comment by szekeres2016** [comment] 2017-03-24 13:50
@Bajoja managed to compile from source, and I can confirm that it works just fine now! I've tested it on Ubuntu/Nautilus and its perfect. The Menu updates as more devices get connected. On Nemo however on Linux Mint 18.1 the menu still only shows a single device for some reason so can't tell if its fixed there or not. But the menu doesn't go away so it probably works but does not display more than one device at a time.

**Comment by Bajoja** [comment] 2017-03-24 14:36
I forget to tell you to replace the kdeconnect-send-nemo to the new one on the source too, do that and tell me

**Comment by szekeres2016** [comment] 2017-03-24 14:56
@Bajoja will do that once I'm done with system rescue. I think some package from Mint are seriously buggy at the moment. My Cinnamon desktop is broken at the moment and fails to recover. Will try again once I manage to fix it somehow...

**Comment by Bajoja** [comment] 2017-03-24 18:09
For Mint you don't need to compile from the source, just copy the new kdeconnect-send-nemo to Nemo extension path, if it not work I will apply the same thing I do with Nautilus otherwise I will consider it stable

**Comment by szekeres2016** [comment] 2017-03-25 11:06
@Bajoja quick question, where exactly shall I put the 'kdeconnect-send-nemo.py' file? I can't find where the current extension is installed to.

**Comment by szekeres2016** [comment] 2017-03-25 12:52
@Bajoja the nemo extension works as well, it does not disappeare anymore but still only lists a single device despite 3 is connected.

**Comment by Bajoja** [comment] 2017-03-25 15:36
@szekeres2016 In this case I will apply the same corrections that I made for Nautilus on Nemo and launch a new realease, Thanks for your patience and support

**Closed** 2017-03-28 17:14 UTC

**Comment by szekeres2016** [comment] 2017-04-06 14:14
I just installed the 0.7 version, and its perfect on Ubuntu with Nautilus. Unfortunately it the Nemo extension just doesn't work, I mean at all. I purged the old package, manually removed the .py file from the extension from the python-nemo/extension and reinstalled. I logged out and back in but there is no KDE Connect send menu, regardless of how many devices are connected. I even tried to kill nemo and start it up again but nothing.

**Comment by Bajoja** [comment] 2017-04-06 19:40
@szekeres2016 you install the nemo-python package? 
Because i test it on a virtual machine with Nemo installed on Ubuntu and it work's.

**Comment by szekeres2016** [comment] 2017-04-07 12:40
I double-checked everything there is no reason for it to not work, but it just doesn't :S I have Nemo 3.2.2 on Mint 18.1 64-bit if that helps. Thank you for the work you put in this project, I really love it! :)

**Comment by Bajoja** [comment] 2017-04-07 12:45
@szekeres2016 Nemo receive some kind of update this days?

**Comment by szekeres2016** [comment] 2017-04-07 12:48
@Bajoja I honestly don't think it did in the last week or so, but maybe some related package did (something  related to python?) if you need any log or anything else just let me know and will try to provide something to help.

**Comment by Bajoja** [comment] 2017-04-07 12:50
I will check this on a Mint Virtual Machine

**Comment by Bajoja** [comment] 2017-04-08 21:14
@szekeres2016 new release with the bug #51 (Nemo and Caja extension not working) solved
